version: "3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  api:
    build: ./backend
    command: npm start
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  frontend:
    build: ../fiery_banner-fe
    volumes:
      - ../fiery_banner-fe:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  mongodata:
