version: "3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  api:
    build: ./backend
    command: npm start
    volumes:
      - ./backend:/app
      - /app/node_modules # anonymous volume for node_modules only
    ports:
      - "8080:8080"
  frontend:
    build: ../fiery_banner-fe
    ports:
      - "3000:3000"
    volumes:
      - ../fiery_banner-fe:/app
volumes:
  mongodata:
