# Use an official NodeJS image as the base image
FROM node:18-alpine3.16

# Set the working directory in the container to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package.json ./

# Install the required dependencies
RUN apk add --no-cache make gcc g++ python3 && \
  npm install && \
  npm rebuild bcrypt --build-from-source && \
  apk del make gcc g++ python3

# Copy the rest of the application files to the container
COPY . .

# Specify the command to run when the container starts
CMD [ "npm", "start" ]
